### ISSUE TITLE
Improving mobile appearance?

### ISSUE THREAD

**Issue by NinjaJc01** [tryhackmeltd/docs.tryhackme.com#54]
![Screenshot_20200505-042146_Firefox](https://user-images.githubusercontent.com/20073818/81032537-25da9580-8e88-11ea-86d7-315edb651b29.jpg)
By the looks of it, the alignment is a bit weird on mobile. The title also breaks over a couple lines.

**Comment by Kent55** [comment]
@NinjaJc01 Thanks for raising this, it's definitely something I have in the backlog, just hadn't got round to drafting up an issue for this.
