### ISSUE TITLE
Broken Link on https://docs.tryhackme.com/docs/room-creation/room-creation-getting-started/

### ISSUE THREAD

**Issue by umair9747** [tryhackmeltd/docs.tryhackme.com#63]
The create room hyperlink is broken and leads to a 404 page not found , this could be changed with
https://tryhackme.com/create-room

**Comment by Kent55** [comment]
Thank you for reporting this! Will look at fixing this today but please feel free to raise a PR if you see this before I manage to get to it.

@all-contributors please add @umair9747 bug

**Comment by Kent55** [comment]
Thanks @umair9747 for the PR! Closing this issue now as resolved in https://github.com/tryhackmeltd/docs.tryhackme.com/pull/71


@all-contributors please add @umair9747 for documentation
