### ISSUE TITLE
The points rewarded text is outdated following the update

### ISSUE THREAD

**Issue by ZultanH** [tryhackmeltd/docs.tryhackme.com#64]
The message for how points are awarded and how much at https://github.com/tryhackmeltd/docs.tryhackme.com/blob/master/docs/rooms/How%20Points%20Work.md is outdated as it states first to answer gets 80 and subsequent answers only receive 30 but this is outdated as can be seen in the image below
![image](https://user-images.githubusercontent.com/43057246/87934803-27087f80-cad3-11ea-9c82-c33fcc5b1051.png)

**Comment by Kent55** [comment]
Thank you for reporting this! Please feel free to make a PR addressing this issue but will look at updating this today!

@all-contributors please add @ZultanH for bug
